#!/bin/bash

# Mobile Testing Script for Perundhu App
# This script helps test mobile layout without external dependencies

echo "📱 Mobile Testing Guide for Perundhu App"
echo "========================================"
echo ""

# Check if development server is running
if curl -s http://localhost:3000 > /dev/null; then
    echo "✅ Development server is running at http://localhost:3000"
else
    echo "❌ Development server is not running. Please start it with:"
    echo "   cd /Users/mchand69/Documents/perundhu/frontend"
    echo "   npm run dev"
    echo ""
    exit 1
fi

echo ""
echo "🔧 Manual Mobile Testing Instructions:"
echo "======================================"
echo ""
echo "1. Open your browser and go to: http://localhost:3000"
echo ""
echo "2. Open Developer Tools:"
echo "   - Chrome/Edge: Press F12 or Ctrl+Shift+I (Cmd+Option+I on Mac)"
echo "   - Firefox: Press F12 or Ctrl+Shift+I (Cmd+Option+I on Mac)"
echo "   - Safari: Press Cmd+Option+I"
echo ""
echo "3. Enable Device Simulation:"
echo "   - Chrome: Click the device icon (📱) in the top-left of dev tools"
echo "   - Firefox: Click the responsive design mode icon"
echo "   - Safari: Develop > Enter Responsive Design Mode"
echo ""
echo "4. Test these mobile viewports:"
echo "   - iPhone SE: 375 x 667"
echo "   - iPhone 12: 390 x 844"
echo "   - Samsung Galaxy S20: 360 x 800"
echo "   - iPad: 768 x 1024"
echo ""
echo "🔍 Elements to Verify on Mobile:"
echo "==============================="
echo ""
echo "Homepage Elements:"
echo "- [ ] Header is visible and not cut off"
echo "- [ ] From/To location inputs are fully visible"
echo "- [ ] Search button is accessible and properly sized"
echo "- [ ] Language switcher is visible"
echo "- [ ] No horizontal scrolling on homepage"
echo ""
echo "Search Results Page Elements:"
echo "- [ ] 'Available Buses' title shows complete text (with 's')"
echo "- [ ] Bus count badge is visible"
echo "- [ ] All sort buttons are visible: Departure, Arrival, Duration, Price"
echo "- [ ] Sort controls scroll horizontally if needed"
echo "- [ ] Search input is accessible"
echo "- [ ] Filter toggle button is visible"
echo "- [ ] Bus items display properly"
echo "- [ ] Bus information displays on single line (no wrapping)"
echo "- [ ] Bus images/icons are fully displayed (not cut off)"
echo "- [ ] Tap functionality works on bus items"
echo ""
echo "📏 Layout Issues to Check:"
echo "========================="
echo "- [ ] No text overflow or truncation"
echo "- [ ] No elements extending beyond screen width"
echo "- [ ] Touch targets are at least 44px for good usability"
echo "- [ ] Spacing between elements is appropriate"
echo "- [ ] Font sizes are readable on mobile"
echo ""
echo "🧪 Quick Test Scenario:"
echo "======================="
echo "1. Navigate to http://localhost:3000"
echo "2. Set mobile viewport (375x667)"
echo "3. Fill 'From' field with 'Chennai'"
echo "4. Fill 'To' field with 'Coimbatore'"
echo "5. Click 'Find Buses' button"
echo "6. Verify all bus list elements are visible"
echo "7. Check that 'Available Buses' text is complete"
echo "8. Verify Price sort button is visible"
echo "9. Tap on a bus item to expand details"
echo "10. Check for any layout issues or cut-off elements"
echo ""
echo "🚨 Known Issues to Verify Fixed:"
echo "==============================="
echo "1. 'Available Buses' missing 's' → Should show 'Available Buses'"
echo "2. Cut-off bus images → Images should be fully visible"
echo "3. Hidden Price sort button → Should be accessible on mobile"
echo "4. Multi-line bus info → Should display on single line"
echo ""
echo "💡 Pro Tips:"
echo "============"
echo "- Use Chrome DevTools Console to check for errors"
echo "- Test both portrait and landscape orientations"
echo "- Try different mobile device presets"
echo "- Check touch scrolling behavior"
echo "- Verify tap targets are large enough"
echo ""
echo "📸 To take screenshots:"
echo "- Right-click and select 'Save screenshot' in DevTools"
echo "- Or use browser's screenshot functionality"
echo ""
echo "🔗 Quick Access:"
echo "==============="
echo "App URL: http://localhost:3000"
echo "DevTools: F12 or Cmd+Option+I"
echo ""
echo "Happy Testing! 🚀"