# Cloud Build configuration for Perundhu
# Comprehensive CI/CD pipeline with quality checks, security scanning, and deployment

steps:
  # ============================================================================
  # QUALITY CHECKS AND CODE ANALYSIS
  # ============================================================================

  # Frontend: Install dependencies and cache
  - name: 'node:18'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd frontend
        echo "Installing frontend dependencies..."
        npm ci --cache .npm --prefer-offline
    id: 'frontend-deps'
    waitFor: ['-']

  # Frontend: ESLint and TypeScript checks
  - name: 'node:18'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd frontend
        echo "Running ESLint..."
        npm run lint
        echo "Running TypeScript type checking..."
        npm run type-check
    id: 'frontend-lint-typecheck'
    waitFor: ['frontend-deps']

  # Frontend: Unit tests with coverage
  - name: 'node:18'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd frontend
        echo "Running frontend unit tests with coverage..."
        npm run test:coverage
    id: 'frontend-tests'
    waitFor: ['frontend-deps']

  # Backend: Download dependencies and validate
  - name: 'gradle:7-jdk17'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd backend
        echo "Downloading backend dependencies..."
        chmod +x gradlew
        ./gradlew dependencies --no-daemon
    id: 'backend-deps'
    waitFor: ['-']

  # Backend: Code quality checks with SpotBugs and Checkstyle
  - name: 'gradle:7-jdk17'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd backend
        echo "Running backend code quality checks..."
        ./gradlew check -x test --no-daemon || true
        echo "Running dependency vulnerability check..."
        ./gradlew dependencyUpdates --no-daemon || true
    id: 'backend-quality'
    waitFor: ['backend-deps']

  # Backend: Unit and Integration tests
  - name: 'gradle:7-jdk17'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd backend
        echo "Running backend unit tests..."
        ./gradlew test --no-daemon
        echo "Running hexagonal architecture tests..."
        ./gradlew hexagonalTest --no-daemon || true
    id: 'backend-tests'
    waitFor: ['backend-deps']

  # Security: OWASP Dependency Check (Free)
  - name: 'owasp/dependency-check:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Running OWASP Dependency Check..."
        mkdir -p /workspace/security-reports
        
        # Check backend dependencies
        if [ -f backend/build.gradle ]; then
          dependency-check.sh \
            --project "Perundhu Backend" \
            --scan backend/ \
            --format JSON \
            --format HTML \
            --out /workspace/security-reports/backend \
            --data /tmp/dependency-check-data || true
        fi
        
        # Check frontend dependencies
        if [ -f frontend/package.json ]; then
          dependency-check.sh \
            --project "Perundhu Frontend" \
            --scan frontend/package*.json \
            --format JSON \
            --format HTML \
            --out /workspace/security-reports/frontend \
            --data /tmp/dependency-check-data || true
        fi
        
        echo "Security scan completed. Reports saved to security-reports/"
    id: 'security-scan'
    waitFor: ['frontend-deps', 'backend-deps']

  # ============================================================================
  # BUILD APPLICATIONS
  # ============================================================================

  # Backend: Build application
  - name: 'gradle:7-jdk17'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd backend
        echo "Building backend application..."
        ./gradlew clean build -x test --no-daemon
        echo "Build completed successfully"
        ls -la build/libs/
    id: 'build-backend'
    waitFor: ['backend-tests', 'backend-quality']

  # Frontend: Build application
  - name: 'node:18'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd frontend
        echo "Building frontend application..."
        npm run build
        echo "Build completed successfully"
        ls -la dist/
    id: 'build-frontend'
    waitFor: ['frontend-tests', 'frontend-lint-typecheck']

  # ============================================================================
  # DOCKER IMAGE BUILDS
  # ============================================================================

  # Backend: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e  # Exit on any error
        echo "Building backend Docker image..."
        docker build \
          -t gcr.io/$PROJECT_ID/perundhu-backend:$BUILD_ID \
          -t gcr.io/$PROJECT_ID/perundhu-backend:$SHORT_SHA \
          -t gcr.io/$PROJECT_ID/perundhu-backend:latest \
          -f backend/Dockerfile \
          backend/
        echo "Backend Docker image built successfully"
    id: 'build-docker-backend'
    waitFor: ['build-backend']

  # Frontend: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e  # Exit on any error
        echo "Building frontend Docker image..."
        docker build \
          -t gcr.io/$PROJECT_ID/perundhu-frontend:$BUILD_ID \
          -t gcr.io/$PROJECT_ID/perundhu-frontend:$SHORT_SHA \
          -t gcr.io/$PROJECT_ID/perundhu-frontend:latest \
          -f frontend/Dockerfile \
          frontend/
        echo "Frontend Docker image built successfully"
    id: 'build-docker-frontend'
    waitFor: ['build-frontend']

  # ============================================================================
  # SECURITY SCANNING ON IMAGES
  # ============================================================================

  # Container vulnerability scanning with Trivy (Free)
  - name: 'aquasec/trivy:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Scanning Docker images for vulnerabilities..."
        mkdir -p /workspace/security-reports/trivy
        
        # Scan backend image
        trivy image \
          --format json \
          --output /workspace/security-reports/trivy/backend-scan.json \
          gcr.io/$PROJECT_ID/perundhu-backend:$BUILD_ID || true
          
        # Scan frontend image  
        trivy image \
          --format json \
          --output /workspace/security-reports/trivy/frontend-scan.json \
          gcr.io/$PROJECT_ID/perundhu-frontend:$BUILD_ID || true
          
        echo "Container vulnerability scanning completed"
    id: 'container-security-scan'
    waitFor: ['build-docker-backend', 'build-docker-frontend']

  # ============================================================================
  # PUSH IMAGES TO REGISTRY
  # ============================================================================

  # Push backend images (all tags)
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e  # Exit on any error
        echo "Pushing backend images to registry..."
        docker push gcr.io/$PROJECT_ID/perundhu-backend:$BUILD_ID
        docker push gcr.io/$PROJECT_ID/perundhu-backend:$SHORT_SHA
        docker push gcr.io/$PROJECT_ID/perundhu-backend:latest
        echo "Backend images pushed successfully"
    id: 'push-backend-image'
    waitFor: ['container-security-scan']

  # Push frontend images (all tags)
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e  # Exit on any error
        echo "Pushing frontend images to registry..."
        docker push gcr.io/$PROJECT_ID/perundhu-frontend:$BUILD_ID
        docker push gcr.io/$PROJECT_ID/perundhu-frontend:$SHORT_SHA
        docker push gcr.io/$PROJECT_ID/perundhu-frontend:latest
        echo "Frontend images pushed successfully"
    id: 'push-frontend-image'
    waitFor: ['container-security-scan']

  # ============================================================================
  # DATABASE MIGRATIONS
  # ============================================================================

  # Run database migrations
  - name: 'gradle:7-jdk17'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd backend
        echo "Running database migrations..."
        ./gradlew flywayInfo \
          -Pflyway.url="jdbc:mysql://google/${_DB_NAME}?socketFactory=com.google.cloud.sql.mysql.SocketFactory&cloudSqlInstance=${_DB_CONNECTION_NAME}&useSSL=false" \
          -Pflyway.user="${_DB_USER}" \
          -Pflyway.password="$(gcloud secrets versions access latest --secret=${_DB_PASSWORD_SECRET} --project=$PROJECT_ID)" \
          --no-daemon
          
        ./gradlew flywayMigrate \
          -Pflyway.url="jdbc:mysql://google/${_DB_NAME}?socketFactory=com.google.cloud.sql.mysql.SocketFactory&cloudSqlInstance=${_DB_CONNECTION_NAME}&useSSL=false" \
          -Pflyway.user="${_DB_USER}" \
          -Pflyway.password="$(gcloud secrets versions access latest --secret=${_DB_PASSWORD_SECRET} --project=$PROJECT_ID)" \
          --no-daemon
        echo "Database migrations completed"
    id: 'migrate-database'
    waitFor: ['push-backend-image']

  # ============================================================================
  # DEPLOY APPLICATIONS
  # ============================================================================

  # Deploy backend to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Deploying backend to Cloud Run..."
        gcloud run deploy perundhu-${_ENVIRONMENT}-backend \
          --image gcr.io/$PROJECT_ID/perundhu-backend:$BUILD_ID \
          --region ${_REGION} \
          --platform managed \
          --allow-unauthenticated \
          --service-account ${_BACKEND_SERVICE_ACCOUNT} \
          --set-env-vars="SPRING_PROFILES_ACTIVE=${_ENVIRONMENT}" \
          --set-env-vars="GCP_PROJECT_ID=$PROJECT_ID" \
          --set-env-vars="DB_NAME=${_DB_NAME}" \
          --set-env-vars="DB_USER=${_DB_USER}" \
          --set-env-vars="DB_CONNECTION_NAME=${_DB_CONNECTION_NAME}" \
          --vpc-connector ${_VPC_CONNECTOR} \
          --vpc-egress private-ranges-only \
          --cpu ${_BACKEND_CPU} \
          --memory ${_BACKEND_MEMORY} \
          --min-instances ${_BACKEND_MIN_INSTANCES} \
          --max-instances ${_BACKEND_MAX_INSTANCES} \
          --timeout 300 \
          --port 8080 \
          --labels="environment=${_ENVIRONMENT},app=perundhu,tier=backend"
        echo "Backend deployment completed"
    id: 'deploy-backend'
    waitFor: ['migrate-database']

  # Deploy frontend to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Deploying frontend to Cloud Run..."
        gcloud run deploy perundhu-${_ENVIRONMENT}-frontend \
          --image gcr.io/$PROJECT_ID/perundhu-frontend:$BUILD_ID \
          --region ${_REGION} \
          --platform managed \
          --allow-unauthenticated \
          --service-account ${_FRONTEND_SERVICE_ACCOUNT} \
          --set-env-vars="ENVIRONMENT=${_ENVIRONMENT}" \
          --set-env-vars="API_BASE_URL=${_API_BASE_URL}" \
          --cpu ${_FRONTEND_CPU} \
          --memory ${_FRONTEND_MEMORY} \
          --min-instances ${_FRONTEND_MIN_INSTANCES} \
          --max-instances ${_FRONTEND_MAX_INSTANCES} \
          --timeout 120 \
          --port 80 \
          --labels="environment=${_ENVIRONMENT},app=perundhu,tier=frontend"
        echo "Frontend deployment completed"
    id: 'deploy-frontend'
    waitFor: ['push-frontend-image', 'deploy-backend']

  # ============================================================================
  # POST-DEPLOYMENT VALIDATION
  # ============================================================================

  # Health check and smoke tests
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Running post-deployment health checks..."
        
        # Get backend URL
        BACKEND_URL=$(gcloud run services describe perundhu-${_ENVIRONMENT}-backend \
          --region=${_REGION} --format='value(status.url)')
        
        # Get frontend URL  
        FRONTEND_URL=$(gcloud run services describe perundhu-${_ENVIRONMENT}-frontend \
          --region=${_REGION} --format='value(status.url)')
        
        echo "Backend URL: $BACKEND_URL"
        echo "Frontend URL: $FRONTEND_URL"
        
        # Wait for services to be ready
        sleep 30
        
        # Test backend health endpoint
        echo "Testing backend health..."
        curl -f "$BACKEND_URL/actuator/health" || exit 1
        
        # Test frontend
        echo "Testing frontend..."
        curl -f "$FRONTEND_URL" || exit 1
        
        echo "All health checks passed!"
        
        # Store URLs for reference
        echo "BACKEND_URL=$BACKEND_URL" >> /workspace/deployment-urls.txt
        echo "FRONTEND_URL=$FRONTEND_URL" >> /workspace/deployment-urls.txt
    id: 'health-checks'
    waitFor: ['deploy-frontend']

  # Generate deployment report
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Generating deployment report..."
        
        cat > /workspace/deployment-report.md << EOF
        # Perundhu Deployment Report
        
        **Build ID:** $BUILD_ID
        **Short SHA:** $SHORT_SHA
        **Environment:** ${_ENVIRONMENT}
        **Region:** ${_REGION}
        **Timestamp:** $(date -u +"%Y-%m-%d %H:%M:%S UTC")
        
        ## Deployed Services
        
        ### Backend
        - **Service:** perundhu-${_ENVIRONMENT}-backend
        - **Image:** gcr.io/$PROJECT_ID/perundhu-backend:$BUILD_ID
        - **URL:** $(cat /workspace/deployment-urls.txt | grep BACKEND_URL | cut -d'=' -f2)
        
        ### Frontend  
        - **Service:** perundhu-${_ENVIRONMENT}-frontend
        - **Image:** gcr.io/$PROJECT_ID/perundhu-frontend:$BUILD_ID
        - **URL:** $(cat /workspace/deployment-urls.txt | grep FRONTEND_URL | cut -d'=' -f2)
        
        ## Quality Checks Performed
        - ✅ Frontend ESLint and TypeScript validation
        - ✅ Frontend unit tests with coverage
        - ✅ Backend unit and integration tests
        - ✅ OWASP dependency vulnerability scanning
        - ✅ Container image vulnerability scanning (Trivy)
        - ✅ Database migrations
        - ✅ Post-deployment health checks
        
        ## Security Reports
        - Backend dependencies: security-reports/backend/
        - Frontend dependencies: security-reports/frontend/
        - Container images: security-reports/trivy/
        
        EOF
        
        echo "Deployment completed successfully!"
        cat /workspace/deployment-report.md
    id: 'generate-report'
    waitFor: ['health-checks']

# ============================================================================
# CONFIGURATION
# ============================================================================

# Substitution variables with defaults
substitutions:
  # Project configuration (automatically provided by Cloud Build, but can be overridden)
  # PROJECT_ID: 'your-project-id'  # Uncomment and set if you need to override
  
  # Environment configuration
  _ENVIRONMENT: 'preprod'
  _REGION: 'us-central1'
  
  # Service accounts
  _BACKEND_SERVICE_ACCOUNT: 'perundhu-${_ENVIRONMENT}-backend@${PROJECT_ID}.iam.gserviceaccount.com'
  _FRONTEND_SERVICE_ACCOUNT: 'perundhu-${_ENVIRONMENT}-frontend@${PROJECT_ID}.iam.gserviceaccount.com'
  
  # Network configuration
  _VPC_CONNECTOR: 'perundhu-${_ENVIRONMENT}-connector'
  
  # Database configuration
  _DB_NAME: 'perundhu'
  _DB_USER: 'perundhu_user'
  _DB_CONNECTION_NAME: '${PROJECT_ID}:${_REGION}:perundhu-${_ENVIRONMENT}-mysql'
  _DB_PASSWORD_SECRET: 'perundhu-${_ENVIRONMENT}-db-password'
  
  # Backend configuration
  _BACKEND_CPU: '1'
  _BACKEND_MEMORY: '2Gi'
  _BACKEND_MIN_INSTANCES: '0'
  _BACKEND_MAX_INSTANCES: '10'
  
  # Frontend configuration  
  _FRONTEND_CPU: '1'
  _FRONTEND_MEMORY: '1Gi'
  _FRONTEND_MIN_INSTANCES: '0'
  _FRONTEND_MAX_INSTANCES: '5'
  _API_BASE_URL: 'https://perundhu-${_ENVIRONMENT}-backend-${PROJECT_ID}.${_REGION}.run.app'

# Build options
options:
  # Use Cloud Logging for better log management
  logging: CLOUD_LOGGING_ONLY
  
  # Use a powerful machine for faster builds
  dynamic_substitutions: true

# Build timeout (20 minutes for comprehensive pipeline)
timeout: '1200s'

# Images to be pushed to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/perundhu-backend:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/perundhu-backend:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/perundhu-backend:latest'
  - 'gcr.io/$PROJECT_ID/perundhu-frontend:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/perundhu-frontend:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/perundhu-frontend:latest'

# Available logs in Cloud Build console
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/${_DB_PASSWORD_SECRET}/versions/latest
      env: 'DB_PASSWORD'

# Artifacts to store (reports, logs, etc.)
artifacts:
  objects:
    location: 'gs://perundhu-${_ENVIRONMENT}-build-artifacts-$PROJECT_ID'
    paths:
      - '/workspace/security-reports/**/*'
      - '/workspace/deployment-report.md'
      - '/workspace/deployment-urls.txt'
      - 'backend/build/reports/**/*'
      - 'frontend/coverage/**/*'