#!/usr/bin/env python3
"""
Simple Location Deduplication Script
Finds and merges exact duplicate location names in the database.
"""

import mysql.connector
from getpass import getpass
import sys

def connect_to_db(password):
    """Connect to the database via Cloud SQL Proxy"""
    try:
        conn = mysql.connector.connect(
            host='127.0.0.1',
            port=3307,
            user='root',
            password=password,
            database='perundhu'
        )
        return conn
    except Exception as e:
        print(f"❌ Connection failed: {e}")
        return None

def find_duplicates(cursor):
    """Find duplicate location names"""
    query = """
    SELECT 
        LOWER(name) as normalized_name,
        COUNT(*) as count,
        GROUP_CONCAT(id ORDER BY id) as ids,
        GROUP_CONCAT(name ORDER BY id) as names,
        GROUP_CONCAT(type ORDER BY id) as types
    FROM locations
    WHERE name IS NOT NULL
    GROUP BY LOWER(name)
    HAVING COUNT(*) > 1
    ORDER BY count DESC, normalized_name
    """
    cursor.execute(query)
    return cursor.fetchall()

def generate_merge_sql(duplicates):
    """Generate SQL to merge duplicates"""
    sql_statements = []
    
    # Tables that reference locations
    fk_updates = [
        ('buses', 'from_location_id'),
        ('buses', 'to_location_id'),
        ('connecting_routes', 'connection_point_id'),
        ('stops', 'location_id'),
    ]
    
    for dup in duplicates:
        ids = [int(x) for x in dup[2].split(',')]
        names = dup[3].split(',')
        types = dup[4].split(',') if dup[4] else []
        
        # Keep the first ID, delete others
        keep_id = ids[0]
        delete_ids = ids[1:]
        
        # Update foreign key references in all tables
        for del_id in delete_ids:
            # Update each table's foreign key
            for table, column in fk_updates:
                sql_statements.append(
                    f"UPDATE {table} SET {column} = {keep_id} WHERE {column} = {del_id};"
                )
            # Update translations (with entity_type check)
            sql_statements.append(
                f"UPDATE translations SET entity_id = {keep_id} WHERE entity_type = 'LOCATION' AND entity_id = {del_id};"
            )
        
        # Delete duplicates
        for del_id in delete_ids:
            sql_statements.append(f"DELETE FROM locations WHERE id = {del_id};")
    
    return sql_statements

def main():
    print("=" * 60)
    print("Simple Location Deduplication")
    print("=" * 60)
    print()
    
    # Get password
    password = getpass("Enter database password: ")
    print()
    
    # Connect
    print("Connecting to database via Cloud SQL Proxy...")
    conn = connect_to_db(password)
    if not conn:
        sys.exit(1)
    
    cursor = conn.cursor()
    print("✅ Connected!")
    print()
    
    # Find duplicates
    print("📊 Finding duplicate locations...")
    duplicates = find_duplicates(cursor)
    
    total_count = len(duplicates)
    total_extra = sum(dup[1] - 1 for dup in duplicates)
    
    print(f"✅ Found {total_count} location names with duplicates")
    print(f"   Total extra records to remove: {total_extra}")
    print()
    
    # Show top duplicates
    print("Top 20 duplicates:")
    for i, dup in enumerate(duplicates[:20], 1):
        name = dup[0]
        count = dup[1]
        ids = dup[2]
        print(f"  {i:2}. {name}: {count}x (IDs: {ids})")
    
    print()
    
    # Generate SQL
    print("📝 Generating deduplication SQL...")
    sql_statements = generate_merge_sql(duplicates)
    
    # Save to file
    output_file = "deduplication.sql"
    with open(output_file, 'w') as f:
        f.write("-- Location Deduplication SQL\n")
        f.write(f"-- Total duplicates to remove: {total_extra}\n")
        f.write("-- Generated by simple-dedup.py\n\n")
        f.write("START TRANSACTION;\n\n")
        for stmt in sql_statements:
            f.write(stmt + "\n")
        f.write("\nCOMMIT;\n")
    
    print(f"✅ SQL saved to: {output_file}")
    
    # Ask user if they want to execute now
    print("\n" + "="*60)
    response = input("Do you want to EXECUTE this deduplication now? (yes/no): ").strip().lower()
    
    if response == 'yes':
        print("\n🔄 Executing deduplication...")
        print("="*60)
        
        try:
            # Execute all SQL statements
            for i, stmt in enumerate(sql_statements, 1):
                if i % 100 == 0:
                    print(f"   Processed {i}/{len(sql_statements)} statements...")
                cursor.execute(stmt)
            
            # Commit the transaction
            conn.commit()
            print(f"\n✅ SUCCESS! Deduplication completed!")
            print(f"   - Updated foreign key references")
            print(f"   - Deleted {len(duplicate_names)} duplicate location names")
            print(f"   - Removed {total_extra} extra records")
            
            # Verify the results
            cursor.execute("SELECT COUNT(*) FROM locations")
            final_count = cursor.fetchone()[0]
            print(f"\n📊 Final location count: {final_count:,}")
            print(f"   Records removed: {total_extra:,}")
            
        except Exception as e:
            print(f"\n❌ ERROR during execution: {e}")
            conn.rollback()
            print("   Transaction rolled back. No changes made.")
            cursor.close()
            conn.close()
            sys.exit(1)
    else:
        print("\n⏭️  Skipped execution. SQL saved to file for manual review.")
        print("\nManual execution options:")
        print("  1. Review the SQL file: cat deduplication.sql")
        print("  2. Test in a transaction:")
        print("     mysql -h 127.0.0.1 -P 3307 -u root -p perundhu < deduplication.sql")
        print("  3. Or apply via Flyway migration")
    
    cursor.close()
    conn.close()

if __name__ == "__main__":
    main()

