# Cloud Build configuration for Perundhu
# This builds and deploys the backend application to Cloud Run

steps:
  # Build the backend application
  - name: 'gradle:7-jdk17'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd backend
        chmod +x gradlew
        ./gradlew clean build -x test
    id: 'build-backend'

  # Build the frontend application
  - name: 'node:18'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd frontend
        npm ci
        npm run build
    id: 'build-frontend'

  # Build Docker image for backend
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/perundhu-backend:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/perundhu-backend:latest'
      - '-f'
      - 'backend/Dockerfile'
      - 'backend/'
    id: 'build-docker-backend'
    waitFor: ['build-backend']

  # Push Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/perundhu-backend:$SHORT_SHA']
    id: 'push-docker-image'
    waitFor: ['build-docker-backend']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy perundhu-${_ENVIRONMENT}-backend \
          --image gcr.io/$PROJECT_ID/perundhu-backend:$SHORT_SHA \
          --region ${_REGION} \
          --platform managed \
          --allow-unauthenticated \
          --service-account ${_SERVICE_ACCOUNT} \
          --set-env-vars="SPRING_PROFILES_ACTIVE=${_ENVIRONMENT}" \
          --set-env-vars="GCP_PROJECT_ID=$PROJECT_ID" \
          --vpc-connector ${_VPC_CONNECTOR} \
          --vpc-egress private-ranges-only \
          --cpu 1 \
          --memory 2Gi \
          --min-instances 1 \
          --max-instances 5 \
          --timeout 300 \
          --port 8080
    id: 'deploy-cloud-run'
    waitFor: ['push-docker-image']

  # Upload frontend to Cloud Storage
  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gsutil -m rsync -r -d frontend/dist gs://${_STATIC_BUCKET}/
        gsutil -m setmeta -h "Cache-Control:public, max-age=3600" gs://${_STATIC_BUCKET}/**
    id: 'deploy-frontend'
    waitFor: ['build-frontend']

  # Run database migrations
  - name: 'gradle:7-jdk17'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd backend
        ./gradlew flywayMigrate \
          -Pflyway.url="jdbc:mysql://google/${_DB_NAME}?socketFactory=com.google.cloud.sql.mysql.SocketFactory&cloudSqlInstance=${_DB_CONNECTION_NAME}" \
          -Pflyway.user="${_DB_USER}" \
          -Pflyway.password="$(gcloud secrets versions access latest --secret=${_DB_PASSWORD_SECRET})"
    id: 'migrate-database'
    waitFor: ['deploy-cloud-run']

# Substitution variables
substitutions:
  _ENVIRONMENT: 'preprod'
  _REGION: 'us-central1'
  _SERVICE_ACCOUNT: 'perundhu-preprod-backend@${PROJECT_ID}.iam.gserviceaccount.com'
  _VPC_CONNECTOR: 'perundhu-preprod-connector'
  _STATIC_BUCKET: 'perundhu-preprod-static-xxxxxxxx'
  _DB_NAME: 'perundhu'
  _DB_USER: 'perundhu_user'
  _DB_CONNECTION_NAME: '${PROJECT_ID}:${_REGION}:perundhu-preprod-mysql'
  _DB_PASSWORD_SECRET: 'perundhu-preprod-db-password'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100
  
# Build timeout
timeout: '1200s'

# Images to be pushed to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/perundhu-backend:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/perundhu-backend:latest'
