-- Fix: The BCrypt hash inserted by V100 for perundhu_admin did not match the
-- intended password (Admin123!@#Change). This migration replaces it with a
-- verified hash generated by htpasswd -bnBC 10.
--
-- Only updates the row if it still contains the original bad V100 hash,
-- so manually changed passwords are NOT overwritten.

UPDATE admin_users
SET password_hash = '$2a$10$cFAUxRHutOd7IVOLFBgJtuFDuGhTNzuZ4v.8uvVvpAIL.dRjhL03u'
WHERE username = 'perundhu_admin'
  AND password_hash = '$2a$10$R0Q5VXD4CuF.0r.AhpaBw.sqisbri7GOjCKjQohnj6tKUze7FBvMu';
